// <auto-generated />
using System;
using Lab6Variant33.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lab6Variant33.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20211227120612_create-database")]
    partial class createdatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lab6Variant33.Models.Appointment_Status_Codes", b =>
                {
                    b.Property<int>("appointment_status_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("appointment_status_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("appointment_status_code");

                    b.ToTable("Appointment_Status_Codes");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Appointments", b =>
                {
                    b.Property<int>("appointment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("appointment_datetime")
                        .HasColumnType("datetime2");

                    b.Property<string>("appointment_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("appointment_end_datetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("appointment_status_code")
                        .HasColumnType("int");

                    b.Property<int?>("appointment_status_codesappointment_status_code")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<int?>("patientspatient_id")
                        .HasColumnType("int");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.Property<int?>("staff_id1")
                        .HasColumnType("int");

                    b.HasKey("appointment_id");

                    b.HasIndex("appointment_status_codesappointment_status_code");

                    b.HasIndex("patientspatient_id");

                    b.HasIndex("staff_id1");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Patient_Records", b =>
                {
                    b.Property<int>("patient_record_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("component_code")
                        .HasColumnType("int");

                    b.Property<int?>("componentscomponent_code")
                        .HasColumnType("int");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<int?>("patientspatient_id")
                        .HasColumnType("int");

                    b.Property<int?>("staff_id")
                        .HasColumnType("int");

                    b.Property<int>("updated_by_staff_id")
                        .HasColumnType("int");

                    b.HasKey("patient_record_id");

                    b.HasIndex("componentscomponent_code");

                    b.HasIndex("patientspatient_id");

                    b.HasIndex("staff_id");

                    b.ToTable("Patient_Records");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Patients", b =>
                {
                    b.Property<int>("patient_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("comanaged_yn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("date_of_birth")
                        .HasColumnType("datetime2");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("height")
                        .HasColumnType("float");

                    b.Property<int>("nhs_number")
                        .HasColumnType("int");

                    b.Property<string>("other_patient_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patient_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("patient_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("weight")
                        .HasColumnType("float");

                    b.HasKey("patient_id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Record_Components", b =>
                {
                    b.Property<int>("component_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("component_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("component_code");

                    b.ToTable("Record_Components");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Roles", b =>
                {
                    b.Property<int>("role_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("role_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("role_code");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff", b =>
                {
                    b.Property<int>("staff_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("other_staff_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_code")
                        .HasColumnType("int");

                    b.Property<int?>("rolesrole_code")
                        .HasColumnType("int");

                    b.Property<string>("staff_birth_date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("staff_categories_code")
                        .HasColumnType("int");

                    b.Property<int?>("staff_categories_code1")
                        .HasColumnType("int");

                    b.Property<string>("staff_first_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_last_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_middle_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staff_qualifications")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staff_id");

                    b.HasIndex("rolesrole_code");

                    b.HasIndex("staff_categories_code1");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff_Categories", b =>
                {
                    b.Property<int>("staff_categories_code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("staff_category_description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staff_categories_code");

                    b.ToTable("Staff_Categories");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff_Patient_Associations", b =>
                {
                    b.Property<int>("association_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("association_details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("association_end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("association_start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("patient_id")
                        .HasColumnType("int");

                    b.Property<int?>("patientspatient_id")
                        .HasColumnType("int");

                    b.Property<int>("staff_id")
                        .HasColumnType("int");

                    b.Property<int?>("staff_id1")
                        .HasColumnType("int");

                    b.HasKey("association_id");

                    b.HasIndex("patientspatient_id");

                    b.HasIndex("staff_id1");

                    b.ToTable("Staff_Patient_Associations");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Appointments", b =>
                {
                    b.HasOne("Lab6Variant33.Models.Appointment_Status_Codes", "appointment_status_codes")
                        .WithMany("appointments")
                        .HasForeignKey("appointment_status_codesappointment_status_code");

                    b.HasOne("Lab6Variant33.Models.Patients", "patients")
                        .WithMany("appointments")
                        .HasForeignKey("patientspatient_id");

                    b.HasOne("Lab6Variant33.Models.Staff", "staff")
                        .WithMany("appointments")
                        .HasForeignKey("staff_id1");

                    b.Navigation("appointment_status_codes");

                    b.Navigation("patients");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Patient_Records", b =>
                {
                    b.HasOne("Lab6Variant33.Models.Record_Components", "components")
                        .WithMany("patient_records")
                        .HasForeignKey("componentscomponent_code");

                    b.HasOne("Lab6Variant33.Models.Patients", "patients")
                        .WithMany("patient_records")
                        .HasForeignKey("patientspatient_id");

                    b.HasOne("Lab6Variant33.Models.Staff", "staff")
                        .WithMany("patient_records")
                        .HasForeignKey("staff_id");

                    b.Navigation("components");

                    b.Navigation("patients");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff", b =>
                {
                    b.HasOne("Lab6Variant33.Models.Roles", "roles")
                        .WithMany("staff")
                        .HasForeignKey("rolesrole_code");

                    b.HasOne("Lab6Variant33.Models.Staff_Categories", "staff_categories")
                        .WithMany("staff")
                        .HasForeignKey("staff_categories_code1");

                    b.Navigation("roles");

                    b.Navigation("staff_categories");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff_Patient_Associations", b =>
                {
                    b.HasOne("Lab6Variant33.Models.Patients", "patients")
                        .WithMany("staff_patient_associations")
                        .HasForeignKey("patientspatient_id");

                    b.HasOne("Lab6Variant33.Models.Staff", "staff")
                        .WithMany("staff_patient_associations")
                        .HasForeignKey("staff_id1");

                    b.Navigation("patients");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Appointment_Status_Codes", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Patients", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("patient_records");

                    b.Navigation("staff_patient_associations");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Record_Components", b =>
                {
                    b.Navigation("patient_records");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Roles", b =>
                {
                    b.Navigation("staff");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("patient_records");

                    b.Navigation("staff_patient_associations");
                });

            modelBuilder.Entity("Lab6Variant33.Models.Staff_Categories", b =>
                {
                    b.Navigation("staff");
                });
#pragma warning restore 612, 618
        }
    }
}
